import type { Course, Day, TimeSlot } from './types';

// Admin password for login
export const ADMIN_PASSWORD = 'DEMO10';

export const DAYS: Day[] = ['ראשון', 'שני', 'שלישי', 'רביעי', 'חמישי'];
export const TIME_SLOTS: TimeSlot[] = ['שעה 1', 'שעה 2', 'שעה 3', 'שעה 4', 'שעה 5', 'שעה 6'];

export const TIME_SLOTS_MAP: Record<TimeSlot, string> = {
  'שעה 1': '8:50 - 9:35',
  'שעה 2': '9:45 - 10:30',
  'שעה 3': '10:45 - 11:30',
  'שעה 4': '12:00 - 12:45',
  'שעה 5': '13:00 - 13:45',
  'שעה 6': '14:00 - 14:45',
};

// Renamed to INITIAL_COURSES to reflect that this is the default state
export const INITIAL_COURSES: Course[] = [
  // יום ראשון
  { id: 1, name: 'חונכות קבוצתית שירה', details: 'כיתה צהובה', day: 'ראשון', timeSlot: 'שעה 1' },
  { id: 2, name: 'חונכות קבוצתית דנה', details: 'כיתה כתומה', day: 'ראשון', timeSlot: 'שעה 1' },
  { id: 3, name: 'חונכות קבוצתית קרן', details: 'כיתה אדומה', day: 'ראשון', timeSlot: 'שעה 1' },
  { id: 4, name: 'חונכות קבוצתית מונה', details: 'כיתה כחולה', day: 'ראשון', timeSlot: 'שעה 1' },
  { id: 5, name: 'חונכות קבוצתית אבי', details: 'כיתה ירוקה', day: 'ראשון', timeSlot: 'שעה 1' },
  { id: 6, name: 'שעת בית / מליאה', details: '', day: 'ראשון', timeSlot: 'שעה 2' },
  { id: 7, name: 'מספרים ופעולות 3 יעל', details: '+ שמעון כיתה אדומה', day: 'ראשון', timeSlot: 'שעה 3' },
  { id: 8, name: 'מיתולוגיה הודית ובודהיזם א-ג ארז', details: 'כיתה כחולה', day: 'ראשון', timeSlot: 'שעה 3' },
  { id: 9, name: 'אנגלית 5 גיא', details: 'כיתה 40', day: 'ראשון', timeSlot: 'שעה 3' },
  { id: 10, name: 'מספרים ופעולות 4 קב\' 2', details: 'איתי כיתה 3', day: 'ראשון', timeSlot: 'שעה 3' },
  { id: 11, name: 'מדע בכל פינה ד-ו קב\' 2', details: 'ניב כיתה 40', day: 'ראשון', timeSlot: 'שעה 3' },
  { id: 12, name: 'מרכז אמנות פתוח', details: 'דודי אמנות', day: 'ראשון', timeSlot: 'שעה 3' },
  { id: 13, name: 'ספורט גד מריוס', details: 'מגרש', day: 'ראשון', timeSlot: 'שעה 3' },
  { id: 14, name: 'ארוחה', details: '', day: 'ראשון', timeSlot: 'שעה 4' },
  { id: 15, name: 'פופ-אפ גד יוני', details: 'כיתה כחולה', day: 'ראשון', timeSlot: 'שעה 5' },
  { id: 16, name: 'צילומים גדולים בהסטוריה ד-ו ארז', details: 'כיתה 20', day: 'ראשון', timeSlot: 'שעה 5' },
  { id: 17, name: 'שירה בלי ציבור דהו קב\' 1', details: 'ניב כיתה 3', day: 'ראשון', timeSlot: 'שעה 5' },
  { id: 18, name: 'אסטרונומיה א-ג ארז', details: 'כיתה אדומה', day: 'ראשון', timeSlot: 'שעה 6' },
  { id: 19, name: 'ערבית מדוברת אבג מונה', details: 'כיתה כחולה', day: 'ראשון', timeSlot: 'שעה 6' },
  { id: 20, name: 'עיתון קהילה ד-ו יוני', details: 'כיתה 20', day: 'ראשון', timeSlot: 'שעה 6' },
  { id: 21, name: 'סטודיו ציור גד דנה', details: 'אמנות', day: 'ראשון', timeSlot: 'שעה 6' },
  { id: 22, name: 'אהבת המוזיקה דהו', details: 'נועם מוזיקה', day: 'ראשון', timeSlot: 'שעה 6' },
  { id: 23, name: 'התנועה שלי קב\' 2 דהו', details: 'נעמה אולם', day: 'ראשון', timeSlot: 'שעה 6' },
  { id: 24, name: 'ספורט גד מריוס', details: 'מגרש', day: 'ראשון', timeSlot: 'שעה 6' },

  // יום שני
  { id: 25, name: 'מלמדים שחמט ב-ו אבי', details: 'כיתה אדומה', day: 'שני', timeSlot: 'שעה 1' },
  { id: 26, name: 'אותיות ומילים 5 חן', details: 'כיתה 20', day: 'שני', timeSlot: 'שעה 1' },
  { id: 27, name: 'מדע בכל פינה ד-ו קב\' 1', details: 'ניב כיתה 40', day: 'שני', timeSlot: 'שעה 1' },
  { id: 28, name: 'מספרים ופעולות 4 קב\' 1', details: 'איתי כיתה 3', day: 'שני', timeSlot: 'שעה 1' },
  { id: 29, name: 'פיסול גד דודי', details: 'אמנות', day: 'שני', timeSlot: 'שעה 1' },
  { id: 30, name: 'מקום לשקט קב\' 1 קרן', details: 'אולם', day: 'שני', timeSlot: 'שעה 2' },
  { id: 31, name: 'חיזוקית עברית 3 טל', details: 'אוריינות', day: 'שני', timeSlot: 'שעה 2' },
  { id: 32, name: 'מספרים ופעולות 2 יעל', details: '+ מונה כיתה צהובה', day: 'שני', timeSlot: 'שעה 2' },
  { id: 33, name: 'אנגלית 3 קב\' 1 מונה', details: 'כיתה כחולה', day: 'שני', timeSlot: 'שעה 2' },
  { id: 34, name: 'אנגלית 4 קב\' 1 קרן', details: 'כיתה 40', day: 'שני', timeSlot: 'שעה 2' },
  { id: 35, name: 'רצי קהילה גד מריוס', details: 'אולם', day: 'שני', timeSlot: 'שעה 2' },
  { id: 36, name: 'אמאדמה ד-ו ניב', details: 'גינה', day: 'שני', timeSlot: 'שעה 2' },
  { id: 37, name: 'אותיות ומילים 3 קב\' 1 טל', details: 'כיתה צהובה', day: 'שני', timeSlot: 'שעה 3' },
  { id: 38, name: 'אותיות ומילים 4 קב\' 1 חן', details: 'כיתה 20', day: 'שני', timeSlot: 'שעה 3' },
  { id: 39, name: 'שעת אבגד במגרש', details: '', day: 'שני', timeSlot: 'שעה 3' },
  { id: 40, name: 'כתיבה יוצרת ד-ו קב\' 1 נעמה', details: 'כיתה 40', day: 'שני', timeSlot: 'שעה 3' },
  { id: 41, name: 'מרכז אמנות פתוח דודי', details: 'אמנות', day: 'שני', timeSlot: 'שעה 3' },
  { id: 42, name: 'כתב תנועה גד דנה', details: 'אולם', day: 'שני', timeSlot: 'שעה 3' },
  { id: 43, name: 'ארוחה', details: '', day: 'שני', timeSlot: 'שעה 4' },
  { id: 44, name: 'ערבית: שפה ותרבות ג-ה מונה', details: 'כיתה כחולה', day: 'שני', timeSlot: 'שעה 5' },
  { id: 45, name: 'מלכים ג-ה אבי', details: 'כיתה 20', day: 'שני', timeSlot: 'שעה 5' },
  { id: 46, name: 'המרכז לפרויקטים מיוחדים קב\' 1 ארז', details: 'כיתה 40', day: 'שני', timeSlot: 'שעה 5' },
  { id: 47, name: 'חיזוקית חשבון 4-7 איתי', details: 'כיתה 3', day: 'שני', timeSlot: 'שעה 5' },
  { id: 48, name: 'הרכב דהו נועם', details: 'מוזיקה', day: 'שני', timeSlot: 'שעה 5' },
  { id: 49, name: 'ריקודי עם מהצעד הראשון א-ו חן', details: 'אולם', day: 'שני', timeSlot: 'שעה 5' },
  { id: 50, name: 'דמויות מופת גד אבי', details: 'כיתה אדומה', day: 'שני', timeSlot: 'שעה 6' },
  { id: 51, name: 'מוזיקה א-ג קב\' 2 נועם', details: 'כיתה ירוקה', day: 'שני', timeSlot: 'שעה 6' },
  { id: 52, name: 'המרכז לפרויקטים מיוחדים קב\' 2 ארז', details: 'כיתה 20', day: 'שני', timeSlot: 'שעה 6' },
  { id: 53, name: 'כתיבה יוצרת דהו קב\' 2 נעמה', details: 'כיתה 40', day: 'שני', timeSlot: 'שעה 6' },

  // יום שלישי
  { id: 54, name: 'אנגלית 3 קב\' 2 מונה', details: 'כיתה כחולה', day: 'שלישי', timeSlot: 'שעה 1' },
  { id: 55, name: 'אנגלית 4 קב\' 2 קרן', details: 'כיתה 40', day: 'שלישי', timeSlot: 'שעה 1' },
  { id: 56, name: 'מרכז אמנות פתוח דודי', details: 'אמנות', day: 'שלישי', timeSlot: 'שעה 1' },
  { id: 57, name: 'מקהלה דהו נועם', details: 'מוזיקה', day: 'שלישי', timeSlot: 'שעה 1' },
  { id: 58, name: 'תאטרון גד שירה', details: 'אולם', day: 'שלישי', timeSlot: 'שעה 1' },
  { id: 59, name: 'מספרים ופעולות 2 יעל', details: '+ מונה כיתה צהובה', day: 'שלישי', timeSlot: 'שעה 2' },
  { id: 60, name: 'אנגלית 3 קב\' 1 מונה', details: 'כיתה כחולה', day: 'שלישי', timeSlot: 'שעה 2' },
  { id: 61, name: 'אנגלית 4 קב\' 1 קרן', details: 'כיתה 40', day: 'שלישי', timeSlot: 'שעה 2' },
  { id: 62, name: 'מספרים ופעולות 4 קב\' 2', details: 'איתי כיתה 3', day: 'שלישי', timeSlot: 'שעה 2' },
  { id: 63, name: 'מרכז תפירה ג-ו חוליאטה', details: 'אמנות', day: 'שלישי', timeSlot: 'שעה 2' },
  { id: 64, name: 'פלמנקו גד דנה', details: 'אולם', day: 'שלישי', timeSlot: 'שעה 2' },
  { id: 65, name: 'מספרים ופעולות 3 יעל', details: '+ נועם כיתה אדומה', day: 'שלישי', timeSlot: 'שעה 3' },
  { id: 66, name: 'פיסול גד דודי', details: 'אמנות', day: 'שלישי', timeSlot: 'שעה 3' },
  { id: 67, name: 'אנגלית 5 גיא', details: 'כיתה 40', day: 'שלישי', timeSlot: 'שעה 3' },
  { id: 68, name: 'מספרים ופעולות 4 קב\' 2', details: 'איתי כיתה 3', day: 'שלישי', timeSlot: 'שעה 3' },
  { id: 69, name: 'מדע בכל פינה ד-ו קב\' 2', details: 'ניב כיתה 40', day: 'שלישי', timeSlot: 'שעה 3' },
  { id: 70, name: 'מספרים ופעולות 5 קב\' 2', details: 'איתי כיתה 3', day: 'שלישי', timeSlot: 'שעה 3' },
  { id: 71, name: 'כדורסל גד מריוס', details: 'מגרש', day: 'שלישי', timeSlot: 'שעה 3' },
  { id: 72, name: 'שעת וועדות', details: '(עד 13:00)', day: 'שלישי', timeSlot: 'שעה 4' },
  { id: 73, name: 'ארוחה', details: '', day: 'שלישי', timeSlot: 'שעה 4' },
  { id: 74, name: 'יום קצר עד 13:30', details: '', day: 'שלישי', timeSlot: 'שעה 5' },
  
  // יום רביעי
  { id: 75, name: 'זמן מסך גד קב\' 2 אבי', details: 'כיתה אדומה', day: 'רביעי', timeSlot: 'שעה 1' },
  { id: 76, name: 'אותיות ומילים 5 חן', details: 'כיתה 20', day: 'רביעי', timeSlot: 'שעה 1' },
  { id: 77, name: 'מספרים ופעולות 4 קב\' 1', details: 'איתי כיתה 3', day: 'רביעי', timeSlot: 'שעה 1' },
  { id: 78, name: 'יוצרים ויוצרות סיפור א-ד חוליאטה', details: 'אמנות', day: 'רביעי', timeSlot: 'שעה 1' },
  { id: 79, name: 'מקהלה דהו נועם', details: 'מוזיקה', day: 'רביעי', timeSlot: 'שעה 1' },
  { id: 80, name: 'אותיות ומילים 2 שירה', details: '+ מונה כיתה צהובה', day: 'רביעי', timeSlot: 'שעה 2' },
  { id: 81, name: 'מוזיקה א-ג קב\' 1 נועם', details: 'כיתה ירוקה', day: 'רביעי', timeSlot: 'שעה 2' },
  { id: 82, name: 'מדע בכל פינה ד-ו קב\' 1', details: 'ניב כיתה 40', day: 'רביעי', timeSlot: 'שעה 2' },
  { id: 83, name: 'המרכז ליצירת מרכזי פעילות קב\' 1 ארז', details: 'כיתה 20', day: 'רביעי', timeSlot: 'שעה 2' },
  { id: 84, name: 'מיתולוגיה הודית ובודהיזם ד-ו ארז', details: 'כיתה כחולה', day: 'רביעי', timeSlot: 'שעה 3' },
  { id: 85, name: 'אסטרונומיה דהו ארז', details: 'כיתה כחולה', day: 'רביעי', timeSlot: 'שעה 3' },
  { id: 86, name: 'ארוחה', details: '', day: 'רביעי', timeSlot: 'שעה 4' },
  { id: 87, name: 'זמן מסך גד קב\' 1 אבי', details: 'כיתה אדומה', day: 'רביעי', timeSlot: 'שעה 4' },
  { id: 88, name: 'מספרים ופעולות 4 קב\' 1', details: 'איתי כיתה 3', day: 'רביעי', timeSlot: 'שעה 4' },
  { id: 89, name: 'הרכב דהו נועם', details: 'מוזיקה', day: 'רביעי', timeSlot: 'שעה 4' },
  { id: 90, name: 'שעת ללא כדורגל', details: 'במגרש', day: 'רביעי', timeSlot: 'שעה 4' },
  { id: 138, name: 'ארוחה', details: '', day: 'רביעי', timeSlot: 'שעה 5' },
  { id: 91, name: 'חיזוקית חשבון 4-7 איתי', details: 'כיתה 3', day: 'רביעי', timeSlot: 'שעה 5' },
  { id: 92, name: 'מלאכות קדומות ותרבויות עתיקות קב\' 1 גד קרן', details: 'אמנות', day: 'רביעי', timeSlot: 'שעה 5' },
  { id: 93, name: 'הרכב דהו נועם', details: 'מוזיקה', day: 'רביעי', timeSlot: 'שעה 5' },
  { id: 94, name: 'ריקודי עם מהצעד השני ב-ו חן', details: 'אולם', day: 'רביעי', timeSlot: 'שעה 5' },
  { id: 95, name: 'אמאדמה א-ג ניב', details: 'גינה', day: 'רביעי', timeSlot: 'שעה 5' },
  { id: 96, name: 'צילומים גדולים בהיסטוריה א-ב ארז', details: 'כיתה צהובה', day: 'רביעי', timeSlot: 'שעה 6' },
  { id: 97, name: 'עבודה זרה גד אבי', details: 'כיתה אדומה', day: 'רביעי', timeSlot: 'שעה 6' },
  { id: 98, name: 'ספרדית דהו חוליאטה', details: 'כיתה 20', day: 'רביעי', timeSlot: 'שעה 6' },
  { id: 99, name: 'עיתון קהילה ד-ו יוני', details: 'כיתה 20', day: 'רביעי', timeSlot: 'שעה 6' },
  { id: 100, name: 'מלאכות קדומות ותרבויות עתיקות קב\' 2 גד קרן', details: 'אמנות', day: 'רביעי', timeSlot: 'שעה 6' },
  { id: 101, name: 'קבוצת שירה דהו נועם', details: 'מוזיקה', day: 'רביעי', timeSlot: 'שעה 6' },

  // יום חמישי
  { id: 102, name: 'אנגלית 3 קב\' 2 מונה', details: 'כיתה כחולה', day: 'חמישי', timeSlot: 'שעה 1' },
  { id: 103, name: 'הספר הכי מפורסם בעולם ג-ו ארז', details: 'כיתה 20', day: 'חמישי', timeSlot: 'שעה 1' },
  { id: 104, name: 'אנגלית 4 קב\' 2 קרן', details: 'כיתה 40', day: 'חמישי', timeSlot: 'שעה 1' },
  { id: 105, name: 'מספרים ופעולות 2 יעל', details: 'כיתה אדומה', day: 'חמישי', timeSlot: 'שעה 2' },
  { id: 106, name: 'אנגלית 3 קב\' 1 מונה', details: 'כיתה כחולה', day: 'חמישי', timeSlot: 'שעה 2' },
  { id: 107, name: 'אנגלית 4 קב\' 1 קרן', details: 'כיתה 40', day: 'חמישי', timeSlot: 'שעה 2' },
  { id: 108, name: 'מספרים ופעולות 4 קב\' 2', details: 'איתי כיתה 3', day: 'חמישי', timeSlot: 'שעה 2' },
  { id: 109, name: 'מרכז אמנות פתוח דודי', details: 'אמנות', day: 'חמישי', timeSlot: 'שעה 2' },
  { id: 110, name: 'מקום לשקט קב\' 2 קרן', details: 'אולם', day: 'חמישי', timeSlot: 'שעה 2' },
  { id: 111, name: 'מספרים ופעולות 3 יעל', details: 'טל כיתה צהובה', day: 'חמישי', timeSlot: 'שעה 3' },
  { id: 112, name: 'חיזוקית עברית 2 שירה', details: 'טל כיתה צהובה', day: 'חמישי', timeSlot: 'שעה 3' },
  { id: 113, name: 'אותיות ומילים 4 קב\' 2 חן', details: 'כיתה 20', day: 'חמישי', timeSlot: 'שעה 3' },
  { id: 114, name: 'מספרים ופעולות 5 קב\' 2', details: 'איתי כיתה 3', day: 'חמישי', timeSlot: 'שעה 3' },
  { id: 115, name: 'ספורט גד מריוס', details: 'מגרש', day: 'חמישי', timeSlot: 'שעה 3' },
  { id: 116, name: 'ארוחה', details: '', day: 'חמישי', timeSlot: 'שעה 4' },
  { id: 117, name: 'חלות', details: '', day: 'חמישי', timeSlot: 'שעה 4' },
  { id: 118, name: 'אותיות ומילים 3 קב\' 1 טל', details: 'כיתה צהובה', day: 'חמישי', timeSlot: 'שעה 4' },
  { id: 119, name: 'התפתחות גוף האדם גד מריוס', details: 'כיתה כחולה', day: 'חמישי', timeSlot: 'שעה 4' },
  { id: 120, name: 'אותיות ומילים 4 קב\' 1 חן', details: 'כיתה 20', day: 'חמישי', timeSlot: 'שעה 4' },
  { id: 121, name: 'התנועה שלי קב\' 1 דהו', details: 'נעמה אולם', day: 'חמישי', timeSlot: 'שעה 4' },
  { id: 122, name: 'שעת בנות במגרש', details: '', day: 'חמישי', timeSlot: 'שעה 4' },
  { id: 123, name: 'ילד.ה בהפתעה ארז', details: 'כיתה צהובה', day: 'חמישי', timeSlot: 'שעה 4' },
  { id: 124, name: 'מספרים ופעולות 5 קב\' 1', details: '2 איתי כיתה 3', day: 'חמישי', timeSlot: 'שעה 4' },
  { id: 125, name: 'ארוחה', details: '', day: 'חמישי', timeSlot: 'שעה 5' },
  { id: 126, name: 'חלות', details: '', day: 'חמישי', timeSlot: 'שעה 5' },
  { id: 127, name: 'הורה בהפתעה קרן', details: 'כיתה צהובה', day: 'חמישי', timeSlot: 'שעה 5' },
  { id: 128, name: 'סדנת מייקרים ד-ו דודי', details: 'אמנות', day: 'חמישי', timeSlot: 'שעה 5' },
  { id: 129, name: 'משחקי חצר גד יוני', details: 'מגרש', day: 'חמישי', timeSlot: 'שעה 5' },
  { id: 130, name: 'חונכות קבוצתית שירה', details: 'כיתה צהובה', day: 'חמישי', timeSlot: 'שעה 6' },
  { id: 131, name: 'חונכות קבוצתית דנה', details: 'כיתה כתומה', day: 'חמישי', timeSlot: 'שעה 6' },
  { id: 132, name: 'חונכות קבוצתית קרן', details: 'כיתה אדומה', day: 'חמישי', timeSlot: 'שעה 6' },
  { id: 133, name: 'חונכות קבוצתית מונה', details: 'כיתה כחולה', day: 'חמישי', timeSlot: 'שעה 6' },
  { id: 134, name: 'חונכות קבוצתית אבי', details: 'כיתה ירוקה', day: 'חמישי', timeSlot: 'שעה 6' },
  { id: 135, name: 'שירה בלי ציבור דהו קב\' 2', details: 'ניב כיתה 3', day: 'חמישי', timeSlot: 'שעה 6' },
  { id: 136, name: 'סדנת מייקרים ד-ו דודי', details: 'אמנות', day: 'חמישי', timeSlot: 'שעה 6' },
  { id: 137, name: 'שעת הו במגרש', details: '', day: 'חמישי', timeSlot: 'שעה 6' },
];