import type { Course, Day, TimeSlot, GradeLevel } from './types';

// Admin password for login
export const ADMIN_PASSWORD = 'DEMO10';

export const DAYS: Day[] = ['ראשון', 'שני', 'שלישי', 'רביעי', 'חמישי'];
export const TIME_SLOTS: TimeSlot[] = ['שעה 1', 'שעה 2', 'שעה 3', 'שעה 4', 'שעה 5', 'שעה 6'];
export const GRADE_LEVELS: GradeLevel[] = ['א-ב', 'ג-ד', 'ה-ו'];


export const TIME_SLOTS_MAP: Record<TimeSlot, string> = {
  'שעה 1': '8:50 - 9:35',
  'שעה 2': '9:45 - 10:30',
  'שעה 3': '10:45 - 11:30',
  'שעה 4': '12:00 - 12:45',
  'שעה 5': '13:00 - 13:45',
  'שעה 6': '14:00 - 14:45',
};

// Renamed to INITIAL_COURSES to reflect that this is the default state
export const INITIAL_COURSES: Course[] = [
  // =================================================================
  // ======================= שכבת ג-ד (Corrected & Full) ==============
  // =================================================================
  // יום ראשון
  { id: 1, name: 'חונכות קבוצתית שירה', details: 'כיתה צהובה', day: 'ראשון', timeSlot: 'שעה 1', gradeLevel: 'ג-ד' },
  { id: 2, name: 'חונכות קבוצתית דנה', details: 'כיתה כתומה', day: 'ראשון', timeSlot: 'שעה 1', gradeLevel: 'ג-ד' },
  { id: 3, name: 'חונכות קבוצתית קרן', details: 'כיתה אדומה', day: 'ראשון', timeSlot: 'שעה 1', gradeLevel: 'ג-ד' },
  { id: 4, name: 'חונכות קבוצתית מונה', details: 'כיתה כחולה', day: 'ראשון', timeSlot: 'שעה 1', gradeLevel: 'ג-ד' },
  { id: 5, name: 'חונכות קבוצתית אבי', details: 'כיתה ירוקה', day: 'ראשון', timeSlot: 'שעה 1', gradeLevel: 'ג-ד' },
  { id: 6, name: 'שעת בית / מליאה', details: '', day: 'ראשון', timeSlot: 'שעה 2', gradeLevel: 'ג-ד' },
  { id: 7, name: 'מספרים ופעולות 3 יעל', details: '+ שמעון כיתה אדומה', day: 'ראשון', timeSlot: 'שעה 3', gradeLevel: 'ג-ד' },
  { id: 8, name: 'מיתולוגיה הודית ובודהיזם ד-ו ארז', details: 'כיתה כחולה', day: 'ראשון', timeSlot: 'שעה 3', gradeLevel: 'ג-ד' },
  { id: 601, name: 'אנגלית 5 גיא', details: 'כיתה 40', day: 'ראשון', timeSlot: 'שעה 3', gradeLevel: 'ג-ד' },
  { id: 602, name: 'מספרים ופעולות 4 קב\' 2 איתי', details: 'כיתה 3', day: 'ראשון', timeSlot: 'שעה 3', gradeLevel: 'ג-ד' },
  { id: 14, name: 'ארוחה', details: '', day: 'ראשון', timeSlot: 'שעה 4', gradeLevel: 'ג-ד' },
  { id: 603, name: 'זמן מסך גד קב\' 1 אבי', details: 'כיתה אדומה', day: 'ראשון', timeSlot: 'שעה 4', gradeLevel: 'ג-ד' },
  { id: 604, name: 'מספרים ופעולות 4 קב\' 1 איתי', details: 'כיתה 3', day: 'ראשון', timeSlot: 'שעה 4', gradeLevel: 'ג-ד' },
  { id: 605, name: 'הרכב דהו נועם', details: 'מוזיקה', day: 'ראשון', timeSlot: 'שעה 4', gradeLevel: 'ג-ד' },
  { id: 606, name: 'שעת ללא כדורגל', details: 'במגרש', day: 'ראשון', timeSlot: 'שעה 4', gradeLevel: 'ג-ד' },
  { id: 15, name: 'פופ-אפ גד יוני', details: 'כיתה כחולה', day: 'ראשון', timeSlot: 'שעה 5', gradeLevel: 'ג-ד' },
  { id: 607, name: 'צילומים גדולים בהסטוריה ד-ו ארז', details: 'כיתה 20', day: 'ראשון', timeSlot: 'שעה 5', gradeLevel: 'ג-ד' },
  { id: 608, name: 'שירה בלי ציבור דהו קב\' 1 ניב', details: 'כיתה 3', day: 'ראשון', timeSlot: 'שעה 5', gradeLevel: 'ג-ד' },
  { id: 18, name: 'אסטרונומיה א-ג ארז', details: 'כיתה אדומה', day: 'ראשון', timeSlot: 'שעה 6', gradeLevel: 'ג-ד' },
  { id: 609, name: 'דמויות מופת גד אבי', details: 'כיתה אדומה', day: 'ראשון', timeSlot: 'שעה 6', gradeLevel: 'ג-ד' },
  { id: 19, name: 'ערבית מדוברת אבג מונה', details: 'כיתה כחולה', day: 'ראשון', timeSlot: 'שעה 6', gradeLevel: 'ג-ד' },
  { id: 610, name: 'מוזיקה א-ג קב\' 2 נועם', details: 'כיתה ירוקה', day: 'ראשון', timeSlot: 'שעה 6', gradeLevel: 'ג-ד' },
  { id: 611, name: 'עיתון קהילה ד-ו יוני', details: 'כיתה 20', day: 'ראשון', timeSlot: 'שעה 6', gradeLevel: 'ג-ד' },
  { id: 21, name: 'סטודיו ציור גד דנה', details: 'אמנות', day: 'ראשון', timeSlot: 'שעה 6', gradeLevel: 'ג-ד' },
  { id: 612, name: 'אהבת המוזיקה דהו נועם', details: 'מוזיקה', day: 'ראשון', timeSlot: 'שעה 6', gradeLevel: 'ג-ד' },
  { id: 613, name: 'התנועה שלי קב\' 2 דהו נעמה', details: 'אולם', day: 'ראשון', timeSlot: 'שעה 6', gradeLevel: 'ג-ד' },
  { id: 24, name: 'ספורט גד מריוס', details: 'מגרש', day: 'ראשון', timeSlot: 'שעה 6', gradeLevel: 'ג-ד' },

  // יום שני
  { id: 614, name: 'מלמדים שחמט ב-ו אבי', details: 'כיתה אדומה', day: 'שני', timeSlot: 'שעה 1', gradeLevel: 'ג-ד' },
  { id: 615, name: 'אותיות ומילים 5 חן', details: 'כיתה 20', day: 'שני', timeSlot: 'שעה 1', gradeLevel: 'ג-ד' },
  { id: 616, name: 'מדע בכל פינה ד-ו קב\' 1 ניב', details: 'כיתה 40', day: 'שני', timeSlot: 'שעה 1', gradeLevel: 'ג-ד' },
  { id: 617, name: 'מספרים ופעולות 4 קב\' 1 איתי', details: 'כיתה 3', day: 'שני', timeSlot: 'שעה 1', gradeLevel: 'ג-ד' },
  { id: 29, name: 'פיסול גד דודי', details: 'אמנות', day: 'שני', timeSlot: 'שעה 1', gradeLevel: 'ג-ד' },
  { id: 618, name: 'מקום לשקט קב\' 1 קרן', details: 'אולם', day: 'שני', timeSlot: 'שעה 1', gradeLevel: 'ג-ד' },
  { id: 31, name: 'חיזוקית עברית 3 טל', details: 'אוריינות', day: 'שני', timeSlot: 'שעה 2', gradeLevel: 'ג-ד' },
  { id: 619, name: 'מספרים ופעולות 2 יעל', details: 'כיתה אדומה', day: 'שני', timeSlot: 'שעה 2', gradeLevel: 'ג-ד' },
  { id: 620, name: 'אנגלית 3 קב\' 1 מונה', details: 'כיתה כחולה', day: 'שני', timeSlot: 'שעה 2', gradeLevel: 'ג-ד' },
  { id: 621, name: 'אנגלית 4 קב\' 1 קרן', details: 'כיתה 40', day: 'שני', timeSlot: 'שעה 2', gradeLevel: 'ג-ד' },
  { id: 35, name: 'רצי קהילה גד מריוס', details: 'אולם', day: 'שני', timeSlot: 'שעה 2', gradeLevel: 'ג-ד' },
  { id: 622, name: 'אמאדמה ד-ו ניב', details: 'גינה', day: 'שני', timeSlot: 'שעה 2', gradeLevel: 'ג-ד' },
  { id: 623, name: 'אותיות ומילים 3 קב\' 1 טל', details: 'כיתה צהובה', day: 'שני', timeSlot: 'שעה 3', gradeLevel: 'ג-ד' },
  { id: 624, name: 'אסטרונומיה דהו ארז', details: 'כיתה כחולה', day: 'שני', timeSlot: 'שעה 3', gradeLevel: 'ג-ד' },
  { id: 625, name: 'אנגלית 5 גיא', details: 'כיתה 40', day: 'שני', timeSlot: 'שעה 3', gradeLevel: 'ג-ד' },
  { id: 626, name: 'מספרים ופעולות 4 קב\' 2 איתי', details: 'כיתה 3', day: 'שני', timeSlot: 'שעה 3', gradeLevel: 'ג-ד' },
  { id: 627, name: 'כתיבה יוצרת ד-ו קב\' 1 נעמה', details: 'כיתה 40', day: 'שני', timeSlot: 'שעה 3', gradeLevel: 'ג-ד' },
  { id: 628, name: 'מרכז אמנות פתוח דודי', details: 'אמנות', day: 'שני', timeSlot: 'שעה 3', gradeLevel: 'ג-ד' },
  { id: 42, name: 'כתב תנועה גד דנה', details: 'אולם', day: 'שני', timeSlot: 'שעה 3', gradeLevel: 'ג-ד' },
  { id: 39, name: 'שעת אבגד במגרש', details: '', day: 'שני', timeSlot: 'שעה 3', gradeLevel: 'ג-ד' },
  { id: 43, name: 'ארוחה', details: '', day: 'שני', timeSlot: 'שעה 4', gradeLevel: 'ג-ד' },
  { id: 629, name: 'ארוחה', details: '', day: 'שני', timeSlot: 'שעה 5', gradeLevel: 'ג-ד' },
  { id: 630, name: 'ערבית: שפה ותרבות ג-ה מונה', details: 'כיתה כחולה', day: 'שני', timeSlot: 'שעה 5', gradeLevel: 'ג-ד' },
  { id: 631, name: 'מלכים ג-ה אבי', details: 'כיתה 20', day: 'שני', timeSlot: 'שעה 5', gradeLevel: 'ג-ד' },
  { id: 632, name: 'המרכז לפרויקטים מיוחדים קב\' 1 ארז', details: 'כיתה 40', day: 'שני', timeSlot: 'שעה 5', gradeLevel: 'ג-ד' },
  { id: 633, name: 'חיזוקית חשבון 4-7 איתי', details: 'כיתה 3', day: 'שני', timeSlot: 'שעה 5', gradeLevel: 'ג-ד' },
  { id: 634, name: 'הרכב דהו נועם', details: 'מוזיקה', day: 'שני', timeSlot: 'שעה 5', gradeLevel: 'ג-ד' },
  { id: 635, name: 'ריקודי עם מהצעד הראשון א-ו חן', details: 'אולם', day: 'שני', timeSlot: 'שעה 5', gradeLevel: 'ג-ד' },
  { id: 636, name: 'דמויות מופת גד אבי', details: 'כיתה אדומה', day: 'שני', timeSlot: 'שעה 6', gradeLevel: 'ג-ד' },
  { id: 637, name: 'מוזיקה א-ג קב\' 2 נועם', details: 'כיתה ירוקה', day: 'שני', timeSlot: 'שעה 6', gradeLevel: 'ג-ד' },
  { id: 638, name: 'המרכז לפרויקטים מיוחדים קב\' 2 ארז', details: 'כיתה 20', day: 'שני', timeSlot: 'שעה 6', gradeLevel: 'ג-ד' },
  { id: 639, name: 'כתיבה יוצרת דהו קב\' 2 נעמה', details: 'כיתה 40', day: 'שני', timeSlot: 'שעה 6', gradeLevel: 'ג-ד' },
  { id: 640, name: 'סטודיו ציור גד דנה', details: 'אמנות', day: 'שני', timeSlot: 'שעה 6', gradeLevel: 'ג-ד' },
  { id: 641, name: 'אהבת המוזיקה דהו נועם', details: 'מוזיקה', day: 'שני', timeSlot: 'שעה 6', gradeLevel: 'ג-ד' },
  { id: 642, name: 'התנועה שלי קב\' 2 דהו נעמה', details: 'אולם', day: 'שני', timeSlot: 'שעה 6', gradeLevel: 'ג-ד' },
  { id: 643, name: 'ספורט גד מריוס', details: 'מגרש', day: 'שני', timeSlot: 'שעה 6', gradeLevel: 'ג-ד' },

  // יום שלישי
  { id: 644, name: 'אנגלית 3 קב\' 2 מונה', details: 'כיתה כחולה', day: 'שלישי', timeSlot: 'שעה 1', gradeLevel: 'ג-ד' },
  { id: 645, name: 'אנגלית 4 קב\' 2 קרן', details: 'כיתה 40', day: 'שלישי', timeSlot: 'שעה 1', gradeLevel: 'ג-ד' },
  { id: 646, name: 'מרכז אמנות פתוח דודי', details: 'אמנות', day: 'שלישי', timeSlot: 'שעה 1', gradeLevel: 'ג-ד' },
  { id: 647, name: 'מקהלה דהו נועם', details: 'מוזיקה', day: 'שלישי', timeSlot: 'שעה 1', gradeLevel: 'ג-ד' },
  { id: 58, name: 'תאטרון גד שירה', details: 'אולם', day: 'שלישי', timeSlot: 'שעה 1', gradeLevel: 'ג-ד' },
  { id: 648, name: 'אותיות ומילים 2 שירה + מונה', details: 'כיתה צהובה', day: 'שלישי', timeSlot: 'שעה 2', gradeLevel: 'ג-ד' },
  { id: 649, name: 'מוזיקה א-ג קב\' 1 נועם', details: 'כיתה ירוקה', day: 'שלישי', timeSlot: 'שעה 2', gradeLevel: 'ג-ד' },
  { id: 650, name: 'מדע בכל פינה ד-ו קב\' 1 ניב', details: 'כיתה 40', day: 'שלישי', timeSlot: 'שעה 2', gradeLevel: 'ג-ד' },
  { id: 651, name: 'מספרים ופעולות 4 קב\' 2 איתי', details: 'כיתה 3', day: 'שלישי', timeSlot: 'שעה 2', gradeLevel: 'ג-ד' },
  { id: 652, name: 'מרכז תפירה ג-ו חוליאטה', details: 'אמנות', day: 'שלישי', timeSlot: 'שעה 2', gradeLevel: 'ג-ד' },
  { id: 64, name: 'פלמנקו גד דנה', details: 'אולם', day: 'שלישי', timeSlot: 'שעה 2', gradeLevel: 'ג-ד' },
  { id: 653, name: 'חיזוקית עברית 2 טל', details: 'כיתה צהובה', day: 'שלישי', timeSlot: 'שעה 3', gradeLevel: 'ג-ד' },
  { id: 66, name: 'פיסול גד דודי', details: 'אמנות', day: 'שלישי', timeSlot: 'שעה 3', gradeLevel: 'ג-ד' },
  { id: 654, name: 'מדע בכל פינה ד-ו קב\' 2 ניב', details: 'כיתה 40', day: 'שלישי', timeSlot: 'שעה 3', gradeLevel: 'ג-ד' },
  { id: 655, name: 'מספרים ופעולות 5 קב\' 2 איתי', details: 'כיתה 3', day: 'שלישי', timeSlot: 'שעה 3', gradeLevel: 'ג-ד' },
  { id: 71, name: 'כדורסל גד מריוס', details: 'מגרש', day: 'שלישי', timeSlot: 'שעה 3', gradeLevel: 'ג-ד' },
  { id: 72, name: 'שעת וועדות', details: '(עד 13:00)', day: 'שלישי', timeSlot: 'שעה 4', gradeLevel: 'ג-ד' },
  { id: 73, name: 'ארוחה', details: '', day: 'שלישי', timeSlot: 'שעה 4', gradeLevel: 'ג-ד' },
  { id: 656, name: 'יום קצר עד 13:30', details: '', day: 'שלישי', timeSlot: 'שעה 5', gradeLevel: 'ג-ד' },
  
  // יום רביעי
  { id: 75, name: 'זמן מסך גד קב\' 2 אבי', details: 'כיתה אדומה', day: 'רביעי', timeSlot: 'שעה 1', gradeLevel: 'ג-ד' },
  { id: 657, name: 'אותיות ומילים 5 חן', details: 'כיתה 20', day: 'רביעי', timeSlot: 'שעה 1', gradeLevel: 'ג-ד' },
  { id: 658, name: 'יוצרים ויוצרות סיפור א-ד חוליאטה', details: 'אמנות', day: 'רביעי', timeSlot: 'שעה 1', gradeLevel: 'ג-ד' },
  { id: 659, name: 'מקהלה דהו נועם', details: 'מוזיקה', day: 'רביעי', timeSlot: 'שעה 1', gradeLevel: 'ג-ד' },
  { id: 660, name: 'מספרים ופעולות 2 יעל', details: 'כיתה אדומה', day: 'רביעי', timeSlot: 'שעה 2', gradeLevel: 'ג-ד' },
  { id: 661, name: 'אנגלית 3 קב\' 1 מונה', details: 'כיתה כחולה', day: 'רביעי', timeSlot: 'שעה 2', gradeLevel: 'ג-ד' },
  { id: 662, name: 'אנגלית 4 קב\' 1 קרן', details: 'כיתה 40', day: 'רביעי', timeSlot: 'שעה 2', gradeLevel: 'ג-ד' },
  { id: 663, name: 'מרכז תפירה ג-ו חוליאטה', details: 'אמנות', day: 'רביעי', timeSlot: 'שעה 2', gradeLevel: 'ג-ד' },
  { id: 664, name: 'אותיות ומילים 3 קב\' 2 טל', details: 'כיתה צהובה', day: 'רביעי', timeSlot: 'שעה 3', gradeLevel: 'ג-ד' },
  { id: 665, name: 'מספרים ופעולות 3 יעל + נועם', details: 'כיתה אדומה', day: 'רביעי', timeSlot: 'שעה 3', gradeLevel: 'ג-ד' },
  { id: 666, name: 'מספרים ופעולות 5 קב\' 1 איתי', details: 'כיתה 3', day: 'רביעי', timeSlot: 'שעה 3', gradeLevel: 'ג-ד' },
  { id: 86, name: 'ארוחה', details: '', day: 'רביעי', timeSlot: 'שעה 4', gradeLevel: 'ג-ד' },
  { id: 87, name: 'זמן מסך גד קב\' 1 אבי', details: 'כיתה אדומה', day: 'רביעי', timeSlot: 'שעה 4', gradeLevel: 'ג-ד' },
  { id: 667, name: 'אותיות ומילים 3 קב\' 1 טל', details: 'כיתה צהובה', day: 'רביעי', timeSlot: 'שעה 4', gradeLevel: 'ג-ד' },
  { id: 119, name: 'התפתחות גוף האדם גד מריוס', details: 'כיתה כחולה', day: 'רביעי', timeSlot: 'שעה 4', gradeLevel: 'ג-ד' },
  { id: 668, name: 'אותיות ומילים 4 קב\' 1 חן', details: 'כיתה 20', day: 'רביעי', timeSlot: 'שעה 4', gradeLevel: 'ג-ד' },
  { id: 669, name: 'התנועה שלי קב\' 1 דהו נעמה', details: 'אולם', day: 'רביעי', timeSlot: 'שעה 4', gradeLevel: 'ג-ד' },
  { id: 90, name: 'שעת ללא כדורגל', details: 'במגרש', day: 'רביעי', timeSlot: 'שעה 4', gradeLevel: 'ג-ד' },
  { id: 138, name: 'ארוחה', details: '', day: 'רביעי', timeSlot: 'שעה 5', gradeLevel: 'ג-ד' },
  { id: 670, name: 'חיזוקית חשבון 4-7 איתי', details: 'כיתה 3', day: 'רביעי', timeSlot: 'שעה 5', gradeLevel: 'ג-ד' },
  { id: 92, name: 'מלאכות קדומות ותרבויות עתיקות קב\' 1 גד קרן', details: 'אמנות', day: 'רביעי', timeSlot: 'שעה 5', gradeLevel: 'ג-ד' },
  { id: 671, name: 'הרכב דהו נועם', details: 'מוזיקה', day: 'רביעי', timeSlot: 'שעה 5', gradeLevel: 'ג-ד' },
  { id: 672, name: 'ריקודי עם מהצעד השני ב-ו חן', details: 'אולם', day: 'רביעי', timeSlot: 'שעה 5', gradeLevel: 'ג-ד' },
  { id: 673, name: 'אמאדמה א-ג ניב', details: 'גינה', day: 'רביעי', timeSlot: 'שעה 5', gradeLevel: 'ג-ד' },
  { id: 674, name: 'צילומים גדולים בהיסטוריה א-ב ארז', details: 'כיתה צהובה', day: 'רביעי', timeSlot: 'שעה 6', gradeLevel: 'ג-ד' },
  { id: 97, name: 'עבודה זרה גד אבי', details: 'כיתה אדומה', day: 'רביעי', timeSlot: 'שעה 6', gradeLevel: 'ג-ד' },
  { id: 675, name: 'ספרדית דהו חוליאטה', details: 'כיתה 20', day: 'רביעי', timeSlot: 'שעה 6', gradeLevel: 'ג-ד' },
  { id: 676, name: 'עיתון קהילה ד-ו יוני', details: 'כיתה 40', day: 'רביעי', timeSlot: 'שעה 6', gradeLevel: 'ג-ד' },
  { id: 100, name: 'מלאכות קדומות ותרבויות עתיקות קב\' 2 גד קרן', details: 'אמנות', day: 'רביעי', timeSlot: 'שעה 6', gradeLevel: 'ג-ד' },
  { id: 677, name: 'קבוצת שירה דהו נועם', details: 'מוזיקה', day: 'רביעי', timeSlot: 'שעה 6', gradeLevel: 'ג-ד' },

  // יום חמישי
  { id: 678, name: 'אנגלית 3 קב\' 2 מונה', details: 'כיתה כחולה', day: 'חמישי', timeSlot: 'שעה 1', gradeLevel: 'ג-ד' },
  { id: 679, name: 'הספר הכי מפורסם בעולם ג-ו ארז', details: 'כיתה 20', day: 'חמישי', timeSlot: 'שעה 1', gradeLevel: 'ג-ד' },
  { id: 680, name: 'אנגלית 4 קב\' 2 קרן', details: 'כיתה 40', day: 'חמישי', timeSlot: 'שעה 1', gradeLevel: 'ג-ד' },
  { id: 681, name: 'אותיות ומילים 2 שירה + מונה', details: 'כיתה צהובה', day: 'חמישי', timeSlot: 'שעה 2', gradeLevel: 'ג-ד' },
  { id: 682, name: 'המרכז ליצירת מרכזי פעילות קב\' 1 ארז', details: 'כיתה 20', day: 'חמישי', timeSlot: 'שעה 2', gradeLevel: 'ג-ד' },
  { id: 683, name: 'אנגלית 5 גיא', details: 'כיתה 40', day: 'חמישי', timeSlot: 'שעה 2', gradeLevel: 'ג-ד' },
  { id: 684, name: 'מספרים ופעולות 4 קב\' 2 איתי', details: 'כיתה 3', day: 'חמישי', timeSlot: 'שעה 2', gradeLevel: 'ג-ד' },
  { id: 685, name: 'מרכז אמנות פתוח דודי', details: 'אמנות', day: 'חמישי', timeSlot: 'שעה 2', gradeLevel: 'ג-ד' },
  { id: 686, name: 'מקום לשקט קב\' 2 קרן', details: 'אולם', day: 'חמישי', timeSlot: 'שעה 2', gradeLevel: 'ג-ד' },
  { id: 687, name: 'מספרים ופעולות 3 יעל + שמעון', details: 'כיתה אדומה', day: 'חמישי', timeSlot: 'שעה 3', gradeLevel: 'ג-ד' },
  { id: 688, name: 'מיתולוגיה הודית ובודהיזם א-ג ארז', details: 'כיתה כחולה', day: 'חמישי', timeSlot: 'שעה 3', gradeLevel: 'ג-ד' },
  { id: 689, name: 'מספרים ופעולות 5 קב\' 1 איתי', details: 'כיתה 3', day: 'חמישי', timeSlot: 'שעה 3', gradeLevel: 'ג-ד' },
  { id: 115, name: 'ספורט גד מריוס', details: 'מגרש', day: 'חמישי', timeSlot: 'שעה 3', gradeLevel: 'ג-ד' },
  { id: 116, name: 'ארוחה', details: '', day: 'חמישי', timeSlot: 'שעה 4', gradeLevel: 'ג-ד' },
  { id: 690, name: 'חלות', details: '', day: 'חמישי', timeSlot: 'שעה 4', gradeLevel: 'ג-ד' },
  { id: 691, name: 'ילד.ה בהפתעה ארז', details: 'כיתה צהובה', day: 'חמישי', timeSlot: 'שעה 4', gradeLevel: 'ג-ד' },
  { id: 692, name: 'מספרים ופעולות 5 קב\' 2 איתי', details: 'כיתה 3', day: 'חמישי', timeSlot: 'שעה 4', gradeLevel: 'ג-ד' },
  { id: 122, name: 'שעת בנות במגרש', details: '', day: 'חמישי', timeSlot: 'שעה 4', gradeLevel: 'ג-ד' },
  { id: 125, name: 'ארוחה', details: '', day: 'חמישי', timeSlot: 'שעה 5', gradeLevel: 'ג-ד' },
  { id: 693, name: 'חלות', details: '', day: 'חמישי', timeSlot: 'שעה 5', gradeLevel: 'ג-ד' },
  { id: 694, name: 'הורה בהפתעה קרן', details: 'כיתה צהובה', day: 'חמישי', timeSlot: 'שעה 5', gradeLevel: 'ג-ד' },
  { id: 695, name: 'סדנת מייקרים ד-ו דודי', details: 'אמנות', day: 'חמישי', timeSlot: 'שעה 5', gradeLevel: 'ג-ד' },
  { id: 696, name: 'משחקי חצר גד יוני', details: 'מגרש', day: 'חמישי', timeSlot: 'שעה 5', gradeLevel: 'ג-ד' },
  { id: 130, name: 'חונכות קבוצתית שירה', details: 'כיתה צהובה', day: 'חמישי', timeSlot: 'שעה 6', gradeLevel: 'ג-ד' },
  { id: 131, name: 'חונכות קבוצתית דנה', details: 'כיתה כתומה', day: 'חמישי', timeSlot: 'שעה 6', gradeLevel: 'ג-ד' },
  { id: 132, name: 'חונכות קבוצתית קרן', details: 'כיתה אדומה', day: 'חמישי', timeSlot: 'שעה 6', gradeLevel: 'ג-ד' },
  { id: 133, name: 'חונכות קבוצתית מונה', details: 'כיתה כחולה', day: 'חמישי', timeSlot: 'שעה 6', gradeLevel: 'ג-ד' },
  { id: 134, name: 'חונכות קבוצתית אבי', details: 'כיתה ירוקה', day: 'חמישי', timeSlot: 'שעה 6', gradeLevel: 'ג-ד' },
  { id: 697, name: 'שירה בלי ציבור דהו קב\' 2 ניב', details: 'כיתה 3', day: 'חמישי', timeSlot: 'שעה 6', gradeLevel: 'ג-ד' },
  { id: 698, name: 'סדנת מייקרים ד-ו דודי', details: 'אמנות', day: 'חמישי', timeSlot: 'שעה 6', gradeLevel: 'ג-ד' },
  { id: 699, name: 'שעת הו במגרש', details: '', day: 'חמישי', timeSlot: 'שעה 6', gradeLevel: 'ג-ד' },

  // =================================================================
  // ========================== שכבת א-ב ============================
  // =================================================================
  // יום ראשון
  { id: 201, name: 'חונכות קבוצתית שירה + מונה', details: 'כיתה צהובה', day: 'ראשון', timeSlot: 'שעה 1', gradeLevel: 'א-ב' },
  { id: 202, name: 'חונכות קבוצתית דנה', details: 'כיתה כתומה', day: 'ראשון', timeSlot: 'שעה 1', gradeLevel: 'א-ב' },
  { id: 203, name: 'חונכות קבוצתית קרן', details: 'כיתה אדומה', day: 'ראשון', timeSlot: 'שעה 1', gradeLevel: 'א-ב' },
  { id: 204, name: 'חונכות קבוצתית מונה', details: 'כיתה כחולה', day: 'ראשון', timeSlot: 'שעה 1', gradeLevel: 'א-ב' },
  { id: 205, name: 'חונכות קבוצתית אבי', details: 'כיתה ירוקה', day: 'ראשון', timeSlot: 'שעה 1', gradeLevel: 'א-ב' },
  { id: 206, name: 'שעת בית / מליאה', details: '', day: 'ראשון', timeSlot: 'שעה 2', gradeLevel: 'א-ב' },
  { id: 207, name: 'אותיות ומילים 1 שירה + מונה', details: 'כיתה צהובה', day: 'ראשון', timeSlot: 'שעה 3', gradeLevel: 'א-ב' },
  { id: 208, name: 'מספרים ופעולות 3 יעל + נועם', details: 'כיתה אדומה', day: 'ראשון', timeSlot: 'שעה 3', gradeLevel: 'א-ב' },
  { id: 209, name: 'ספורט א-ב מריוס', details: 'אולם', day: 'ראשון', timeSlot: 'שעה 3', gradeLevel: 'א-ב' },
  { id: 210, name: 'ארוחה', details: '', day: 'ראשון', timeSlot: 'שעה 4', gradeLevel: 'א-ב' },
  { id: 211, name: 'גוף האדם א-ב מריוס', details: 'כיתה צהובה', day: 'ראשון', timeSlot: 'שעה 4', gradeLevel: 'א-ב' },
  { id: 212, name: 'שעת ללא כדורגל', details: 'במגרש', day: 'ראשון', timeSlot: 'שעה 4', gradeLevel: 'א-ב' },
  { id: 213, name: 'ארוחה', details: '', day: 'ראשון', timeSlot: 'שעה 5', gradeLevel: 'א-ב' },
  { id: 214, name: 'סטודיו ציור א-ב דנה', details: 'אמנות', day: 'ראשון', timeSlot: 'שעה 5', gradeLevel: 'א-ב' },
  { id: 215, name: 'חיזוקית עברית 1 שירה', details: 'כיתה צהובה', day: 'ראשון', timeSlot: 'שעה 6', gradeLevel: 'א-ב' },
  { id: 216, name: 'אסטרונומיה א-ג ארז', details: 'כיתה אדומה', day: 'ראשון', timeSlot: 'שעה 6', gradeLevel: 'א-ב' },
  { id: 217, name: 'ערבית מדוברת א-ב-ג מונה', details: 'כיתה כחולה', day: 'ראשון', timeSlot: 'שעה 6', gradeLevel: 'א-ב' },

  // יום שני
  { id: 218, name: 'אותיות ומילים 1 שירה', details: 'כיתה צהובה', day: 'שני', timeSlot: 'שעה 1', gradeLevel: 'א-ב' },
  { id: 219, name: 'מלמדים שחמט ב-ו אבי', details: 'כיתה אדומה', day: 'שני', timeSlot: 'שעה 1', gradeLevel: 'א-ב' },
  { id: 220, name: 'מקום לשקט קב\' 1 קרן', details: 'אולם', day: 'שני', timeSlot: 'שעה 1', gradeLevel: 'א-ב' },
  { id: 221, name: 'חיזוקית עברית 3 טל', details: 'אוריינות', day: 'שני', timeSlot: 'שעה 1', gradeLevel: 'א-ב' },
  { id: 222, name: 'מספרים ופעולות 2 יעל', details: 'כיתה אדומה', day: 'שני', timeSlot: 'שעה 2', gradeLevel: 'א-ב' },
  { id: 223, name: 'אנגלית 3 קב\' 1 מונה', details: 'כיתה כחולה', day: 'שני', timeSlot: 'שעה 2', gradeLevel: 'א-ב' },
  { id: 224, name: 'פיסול א-ב דודי', details: 'אמנות', day: 'שני', timeSlot: 'שעה 2', gradeLevel: 'א-ב' },
  { id: 225, name: 'אותיות ומילים 3 קב\' 1 טל', details: 'כיתה צהובה', day: 'שני', timeSlot: 'שעה 3', gradeLevel: 'א-ב' },
  { id: 226, name: 'דמויות מופת א-ב אבי', details: 'כיתה אדומה', day: 'שני', timeSlot: 'שעה 3', gradeLevel: 'א-ב' },
  { id: 227, name: 'מרכז אמנות פתוח דודי', details: 'אמנות', day: 'שני', timeSlot: 'שעה 3', gradeLevel: 'א-ב' },
  { id: 228, name: 'ארוחה', details: '', day: 'שני', timeSlot: 'שעה 4', gradeLevel: 'א-ב' },
  { id: 229, name: 'אותיות ומילים 3 קב\' 2 טל', details: 'כיתה צהובה', day: 'שני', timeSlot: 'שעה 4', gradeLevel: 'א-ב' },
  { id: 230, name: 'המרכז ליצירת מרכזי פעילות קב\' 2 ארז', details: 'כיתה כחולה', day: 'שני', timeSlot: 'שעה 4', gradeLevel: 'א-ב' },
  { id: 231, name: 'מרכז אמנות פתוח דודי', details: 'אמנות', day: 'שני', timeSlot: 'שעה 4', gradeLevel: 'א-ב' },
  { id: 232, name: 'ארוחה', details: '', day: 'שני', timeSlot: 'שעה 5', gradeLevel: 'א-ב' },
  { id: 233, name: 'המרכז לפרויקטים מיוחדים קב\' 1 ארז', details: 'כיתה 40', day: 'שני', timeSlot: 'שעה 5', gradeLevel: 'א-ב' },
  { id: 234, name: 'ריקודי עם מהצעד הראשון א-ו חן', details: 'אולם', day: 'שני', timeSlot: 'שעה 5', gradeLevel: 'א-ב' },
  { id: 235, name: 'כדורגל א-ב מריוס', details: 'מגרש', day: 'שני', timeSlot: 'שעה 5', gradeLevel: 'א-ב' },
  { id: 236, name: 'מוזיקה א-ג קב\' 2 נועם', details: 'כיתה ירוקה', day: 'שני', timeSlot: 'שעה 6', gradeLevel: 'א-ב' },
  { id: 237, name: 'המרכז לפרויקטים מיוחדים קב\' 2 ארז', details: 'כיתה 20', day: 'שני', timeSlot: 'שעה 6', gradeLevel: 'א-ב' },
  { id: 238, name: 'כתב תנועה א-ב דנה', details: 'אולם', day: 'שני', timeSlot: 'שעה 6', gradeLevel: 'א-ב' },
  
  // יום שלישי
  { id: 239, name: 'מספרים ופעולות 1 יעל', details: 'כיתה אדומה', day: 'שלישי', timeSlot: 'שעה 1', gradeLevel: 'א-ב' },
  { id: 240, name: 'אנגלית 3 קב\' 2 מונה', details: 'כיתה כחולה', day: 'שלישי', timeSlot: 'שעה 1', gradeLevel: 'א-ב' },
  { id: 241, name: 'מרכז אמנות פתוח דודי', details: 'אמנות', day: 'שלישי', timeSlot: 'שעה 1', gradeLevel: 'א-ב' },
  { id: 242, name: 'אותיות ומילים 2 שירה + מונה', details: 'כיתה צהובה', day: 'שלישי', timeSlot: 'שעה 2', gradeLevel: 'א-ב' },
  { id: 243, name: 'מוזיקה א-ג קב\' 1 נועם', details: 'כיתה ירוקה', day: 'שלישי', timeSlot: 'שעה 2', gradeLevel: 'א-ב' },
  { id: 244, name: 'חיזוקית עברית 1 שירה', details: 'כיתה אדומה', day: 'שלישי', timeSlot: 'שעה 3', gradeLevel: 'א-ב' },
  { id: 245, name: 'פלמנקו א-ב דנה', details: 'אולם', day: 'שלישי', timeSlot: 'שעה 3', gradeLevel: 'א-ב' },
  { id: 246, name: 'שעת אבגד במגרש', details: '', day: 'שלישי', timeSlot: 'שעה 3', gradeLevel: 'א-ב' },
  { id: 247, name: 'מרכז תפירה א-ב חוליאטה', details: 'אמנות', day: 'שלישי', timeSlot: 'שעה 3', gradeLevel: 'א-ב' },
  { id: 248, name: 'שעת וועדות (עד 13:00)', details: '', day: 'שלישי', timeSlot: 'שעה 4', gradeLevel: 'א-ב' },
  { id: 249, name: 'ארוחה', details: '', day: 'שלישי', timeSlot: 'שעה 4', gradeLevel: 'א-ב' },
  { id: 250, name: 'מפגשי סוף יום', details: '', day: 'שלישי', timeSlot: 'שעה 5', gradeLevel: 'א-ב' },
  { id: 251, name: 'יום קצר', details: '', day: 'שלישי', timeSlot: 'שעה 5', gradeLevel: 'א-ב' },

  // יום רביעי
  { id: 252, name: 'אותיות ומילים 1 שירה + מונה', details: 'כיתה צהובה', day: 'רביעי', timeSlot: 'שעה 1', gradeLevel: 'א-ב' },
  { id: 253, name: 'יוצרים ויוצרות סיפור א-ד חוליאטה', details: 'אמנות', day: 'רביעי', timeSlot: 'שעה 1', gradeLevel: 'א-ב' },
  { id: 254, name: 'מספרים ופעולות 2 יעל', details: 'כיתה אדומה', day: 'רביעי', timeSlot: 'שעה 2', gradeLevel: 'א-ב' },
  { id: 255, name: 'אנגלית 3 קב\' 1 מונה', details: 'כיתה כחולה', day: 'רביעי', timeSlot: 'שעה 2', gradeLevel: 'א-ב' },
  { id: 256, name: 'ספורט א-ב מריוס', details: 'אולם', day: 'רביעי', timeSlot: 'שעה 2', gradeLevel: 'א-ב' },
  { id: 257, name: 'חיזוקית עברית 2 טל', details: 'כיתה צהובה', day: 'רביעי', timeSlot: 'שעה 3', gradeLevel: 'א-ב' },
  { id: 258, name: 'מספרים ופעולות 3 יעל + נועם', details: 'כיתה אדומה', day: 'רביעי', timeSlot: 'שעה 3', gradeLevel: 'א-ב' },
  { id: 259, name: 'הספר הכי מפורסם בעולם א-ב ארז', details: 'כיתה כחולה', day: 'רביעי', timeSlot: 'שעה 3', gradeLevel: 'א-ב' },
  { id: 260, name: 'ארוחה', details: '', day: 'רביעי', timeSlot: 'שעה 4', gradeLevel: 'א-ב' },
  { id: 261, name: 'אותיות ומילים 3 קב\' 1 טל', details: 'כיתה צהובה', day: 'רביעי', timeSlot: 'שעה 4', gradeLevel: 'א-ב' },
  { id: 262, name: 'עבודה זרה א-ב אבי', details: 'כיתה אדומה', day: 'רביעי', timeSlot: 'שעה 4', gradeLevel: 'א-ב' },
  { id: 263, name: 'רצי קהילה א-ב מריוס', details: 'אולם', day: 'רביעי', timeSlot: 'שעה 4', gradeLevel: 'א-ב' },
  { id: 264, name: 'שעת בנות במגרש', details: '', day: 'רביעי', timeSlot: 'שעה 4', gradeLevel: 'א-ב' },
  { id: 265, name: 'ארוחה', details: '', day: 'רביעי', timeSlot: 'שעה 5', gradeLevel: 'א-ב' },
  { id: 266, name: 'ריקודי עם מהצעד השני ב-ו חן', details: 'אולם', day: 'רביעי', timeSlot: 'שעה 5', gradeLevel: 'א-ב' },
  { id: 267, name: 'אמאדמה א-ג ניב', details: 'גינה', day: 'רביעי', timeSlot: 'שעה 5', gradeLevel: 'א-ב' },
  { id: 268, name: 'צילומים גדולים בהיסטוריה א-ב ארז', details: 'כיתה צהובה', day: 'רביעי', timeSlot: 'שעה 6', gradeLevel: 'א-ב' },
  { id: 269, name: 'כדורסל א-ב מריוס', details: 'אולם', day: 'רביעי', timeSlot: 'שעה 6', gradeLevel: 'א-ב' },
  
  // יום חמישי
  { id: 270, name: 'מספרים ופעולות 1 יעל', details: 'כיתה צהובה', day: 'חמישי', timeSlot: 'שעה 1', gradeLevel: 'א-ב' },
  { id: 271, name: 'אנגלית 3 קב\' 2 מונה', details: 'כיתה כחולה', day: 'חמישי', timeSlot: 'שעה 1', gradeLevel: 'א-ב' },
  { id: 272, name: 'פיסול א-ב דודי', details: 'אמנות', day: 'חמישי', timeSlot: 'שעה 1', gradeLevel: 'א-ב' },
  { id: 273, name: 'אותיות ומילים 2 שירה + מונה', details: 'כיתה צהובה', day: 'חמישי', timeSlot: 'שעה 2', gradeLevel: 'א-ב' },
  { id: 274, name: 'המרכז ליצירת מרכזי פעילות קב\' 1 ארז', details: 'כיתה 20', day: 'חמישי', timeSlot: 'שעה 2', gradeLevel: 'א-ב' },
  { id: 275, name: 'מרכז אמנות פתוח דודי', details: 'אמנות', day: 'חמישי', timeSlot: 'שעה 2', gradeLevel: 'א-ב' },
  { id: 276, name: 'מקום לשקט קב\' 2 קרן', details: 'אולם', day: 'חמישי', timeSlot: 'שעה 2', gradeLevel: 'א-ב' },
  { id: 277, name: 'מספרים ופעולות 3 יעל + שמעון', details: 'כיתה אדומה', day: 'חמישי', timeSlot: 'שעה 3', gradeLevel: 'א-ב' },
  { id: 278, name: 'מיתולוגיה הודית ובודהיזם א-ג ארז', details: 'כיתה כחולה', day: 'חמישי', timeSlot: 'שעה 3', gradeLevel: 'א-ב' },
  { id: 279, name: 'תאטרון בקטנה שירה', details: 'אולם', day: 'חמישי', timeSlot: 'שעה 3', gradeLevel: 'א-ב' },
  { id: 280, name: 'ארוחה', details: '', day: 'חמישי', timeSlot: 'שעה 4', gradeLevel: 'א-ב' },
  { id: 281, name: 'חלות', details: '', day: 'חמישי', timeSlot: 'שעה 4', gradeLevel: 'א-ב' },
  { id: 282, name: 'ילד.ה בהפתעה ארז', details: 'כיתה צהובה', day: 'חמישי', timeSlot: 'שעה 4', gradeLevel: 'א-ב' },
  { id: 283, name: 'ארוחה', details: '', day: 'חמישי', timeSlot: 'שעה 5', gradeLevel: 'א-ב' },
  { id: 284, name: 'חלות', details: '', day: 'חמישי', timeSlot: 'שעה 5', gradeLevel: 'א-ב' },
  { id: 285, name: 'הורה בהפתעה קרן', details: 'כיתה צהובה', day: 'חמישי', timeSlot: 'שעה 5', gradeLevel: 'א-ב' },
  { id: 286, name: 'חונכות קבוצתית שירה', details: 'כיתה צהובה', day: 'חמישי', timeSlot: 'שעה 6', gradeLevel: 'א-ב' },
  { id: 287, name: 'חונכות קבוצתית דנה', details: 'כיתה כתומה', day: 'חמישי', timeSlot: 'שעה 6', gradeLevel: 'א-ב' },
  { id: 288, name: 'חונכות קבוצתית קרן', details: 'כיתה אדומה', day: 'חמישי', timeSlot: 'שעה 6', gradeLevel: 'א-ב' },
  { id: 289, name: 'חונכות קבוצתית מונה', details: 'כיתה כחולה', day: 'חמישי', timeSlot: 'שעה 6', gradeLevel: 'א-ב' },
  { id: 290, name: 'חונכות קבוצתית אבי', details: 'כיתה ירוקה', day: 'חמישי', timeSlot: 'שעה 6', gradeLevel: 'א-ב' },
  { id: 291, name: 'שעת א-ב במגרש', details: '', day: 'חמישי', timeSlot: 'שעה 6', gradeLevel: 'א-ב' },

  // =================================================================
  // ========================== שכבת ה-ו ============================
  // =================================================================
  // יום ראשון
  { id: 401, name: 'חונכות קבוצתית נעמה', details: 'כיתה 20', day: 'ראשון', timeSlot: 'שעה 1', gradeLevel: 'ה-ו' },
  { id: 402, name: 'חונכות קבוצתית ניב', details: 'כיתה 40', day: 'ראשון', timeSlot: 'שעה 1', gradeLevel: 'ה-ו' },
  { id: 403, name: 'חונכות קבוצתית יוני', details: 'כיתה 3', day: 'ראשון', timeSlot: 'שעה 1', gradeLevel: 'ה-ו' },
  { id: 404, name: 'שעת בית / מליאה', details: '', day: 'ראשון', timeSlot: 'שעה 2', gradeLevel: 'ה-ו' },
  { id: 405, name: 'מיתולוגיה הודית ובודהיזם ד-ו ארז', details: 'כיתה כחולה', day: 'ראשון', timeSlot: 'שעה 3', gradeLevel: 'ה-ו' },
  { id: 406, name: 'אנגלית 5 גיא', details: 'כיתה 40', day: 'ראשון', timeSlot: 'שעה 3', gradeLevel: 'ה-ו' },
  { id: 407, name: 'מספרים ופעולות 4 קב\' 2 איתי', details: 'כיתה 3', day: 'ראשון', timeSlot: 'שעה 3', gradeLevel: 'ה-ו' },
  { id: 408, name: 'ארוחה', details: '', day: 'ראשון', timeSlot: 'שעה 4', gradeLevel: 'ה-ו' },
  { id: 409, name: 'צילומים גדולים בהסטוריה ד-ו ארז', details: 'כיתה 20', day: 'ראשון', timeSlot: 'שעה 5', gradeLevel: 'ה-ו' },
  { id: 410, name: 'שירה בלי ציבור ד-ה-ו קב\' 1 ניב', details: 'כיתה 3', day: 'ראשון', timeSlot: 'שעה 5', gradeLevel: 'ה-ו' },
  { id: 411, name: 'ספורט ה-ו מריוס', details: 'אולם', day: 'ראשון', timeSlot: 'שעה 5', gradeLevel: 'ה-ו' },
  { id: 412, name: 'עיתון קהילה ד-ו יוני', details: 'כיתה 20', day: 'ראשון', timeSlot: 'שעה 6', gradeLevel: 'ה-ו' },
  { id: 413, name: 'מידת הזהב ניב', details: 'כיתה 40', day: 'ראשון', timeSlot: 'שעה 6', gradeLevel: 'ה-ו' },
  { id: 414, name: 'יצירות מופת ה-ו אבי', details: 'כיתה 3', day: 'ראשון', timeSlot: 'שעה 6', gradeLevel: 'ה-ו' },
  { id: 415, name: 'אהבת המוזיקה ד-ה-ו נועם', details: 'מוזיקה', day: 'ראשון', timeSlot: 'שעה 6', gradeLevel: 'ה-ו' },
  { id: 416, name: 'התנועה שלי קב\' 2 ד-ה-ו נעמה', details: 'אולם', day: 'ראשון', timeSlot: 'שעה 6', gradeLevel: 'ה-ו' },

  // יום שני
  { id: 417, name: 'מלמדים שחמט ב-ו אבי', details: 'כיתה אדומה', day: 'שני', timeSlot: 'שעה 1', gradeLevel: 'ה-ו' },
  { id: 418, name: 'אותיות ומילים 5 חן', details: 'כיתה 20', day: 'שני', timeSlot: 'שעה 1', gradeLevel: 'ה-ו' },
  { id: 419, name: 'מדע בכל פינה ד-ו קב\' 1 איתי', details: 'כיתה 3', day: 'שני', timeSlot: 'שעה 1', gradeLevel: 'ה-ו' },
  { id: 420, name: 'מספרים ופעולות 4 קב\' 1 איתי', details: 'כיתה 3', day: 'שני', timeSlot: 'שעה 1', gradeLevel: 'ה-ו' },
  { id: 421, name: 'מקום לשקט קב\' 1 קרן', details: 'אולם', day: 'שני', timeSlot: 'שעה 1', gradeLevel: 'ה-ו' },
  { id: 422, name: 'אותיות ומילים 6 קב\' 2 חן', details: 'כיתה 20', day: 'שני', timeSlot: 'שעה 2', gradeLevel: 'ה-ו' },
  { id: 423, name: 'אנגלית 4 קב\' 1 קרן', details: 'כיתה 40', day: 'שני', timeSlot: 'שעה 2', gradeLevel: 'ה-ו' },
  { id: 424, name: 'מספרים ופעולות 6 קב\' 2 איתי', details: 'כיתה 3', day: 'שני', timeSlot: 'שעה 2', gradeLevel: 'ה-ו' },
  { id: 425, name: 'אמאדמה ד-ו ניב', details: 'גינה', day: 'שני', timeSlot: 'שעה 2', gradeLevel: 'ה-ו' },
  { id: 426, name: 'אסטרונומיה ד-ה-ו ארז', details: 'כיתה כחולה', day: 'שני', timeSlot: 'שעה 3', gradeLevel: 'ה-ו' },
  { id: 427, name: 'אותיות ומילים 6 קב\' 1 חן', details: 'כיתה 20', day: 'שני', timeSlot: 'שעה 3', gradeLevel: 'ה-ו' },
  { id: 428, name: 'כתיבה יוצרת ד-ו קב\' 1 נעמה', details: 'כיתה 40', day: 'שני', timeSlot: 'שעה 3', gradeLevel: 'ה-ו' },
  { id: 429, name: 'מספרים ופעולות 4 קב\' 2 איתי', details: 'כיתה 3', day: 'שני', timeSlot: 'שעה 3', gradeLevel: 'ה-ו' },
  { id: 430, name: 'מרכז אמנות פתוח דודי', details: 'אמנות', day: 'שני', timeSlot: 'שעה 3', gradeLevel: 'ה-ו' },
  { id: 431, name: 'ארוחה', details: '', day: 'שני', timeSlot: 'שעה 4', gradeLevel: 'ה-ו' },
  { id: 432, name: 'המרכז ליצירת מרכזי פעילות קב\' 2 ארז', details: 'כיתה כחולה', day: 'שני', timeSlot: 'שעה 4', gradeLevel: 'ה-ו' },
  { id: 433, name: 'אנגלית 6 קב\' 1 גיא', details: 'כיתה 40', day: 'שני', timeSlot: 'שעה 4', gradeLevel: 'ה-ו' },
  { id: 434, name: 'מספרים ופעולות 7 1 איתי', details: 'כיתה 3', day: 'שני', timeSlot: 'שעה 4', gradeLevel: 'ה-ו' },
  { id: 435, name: 'הרכב ד-ה-ו נועם', details: 'מוזיקה', day: 'שני', timeSlot: 'שעה 4', gradeLevel: 'ה-ו' },
  { id: 436, name: 'מרכז אמנות פתוח דודי', details: 'אמנות', day: 'שני', timeSlot: 'שעה 4', gradeLevel: 'ה-ו' },
  { id: 437, name: 'ארוחה', details: '', day: 'שני', timeSlot: 'שעה 5', gradeLevel: 'ה-ו' },
  { id: 438, name: 'ערבית: שפה ותרבות ג-ה מונה', details: 'כיתה כחולה', day: 'שני', timeSlot: 'שעה 5', gradeLevel: 'ה-ו' },
  { id: 439, name: 'מלכים ג-ה אבי', details: 'כיתה 20', day: 'שני', timeSlot: 'שעה 5', gradeLevel: 'ה-ו' },
  { id: 440, name: 'המרכז לפרויקטים מיוחדים קב\' 1 ארז', details: 'כיתה 40', day: 'שני', timeSlot: 'שעה 5', gradeLevel: 'ה-ו' },
  { id: 441, name: 'חיזוקית חשבון 4-7 איתי', details: 'כיתה 3', day: 'שני', timeSlot: 'שעה 5', gradeLevel: 'ה-ו' },
  { id: 442, name: 'הרכב ד-ה-ו נועם', details: 'מוזיקה', day: 'שני', timeSlot: 'שעה 5', gradeLevel: 'ה-ו' },
  { id: 443, name: 'ריקודי עם מהצעד הראשון א-ו חן', details: 'אולם', day: 'שני', timeSlot: 'שעה 5', gradeLevel: 'ה-ו' },
  { id: 444, name: 'המרכז לפרויקטים מיוחדים קב\' 2 ארז', details: 'כיתה 20', day: 'שני', timeSlot: 'שעה 6', gradeLevel: 'ה-ו' },
  { id: 445, name: 'כתיבה יוצרת ד-ה-ו קב\' 2 נעמה', details: 'כיתה 40', day: 'שני', timeSlot: 'שעה 6', gradeLevel: 'ה-ו' },

  // יום שלישי
  { id: 446, name: 'אותיות ומילים 7 חן', details: 'כיתה 20', day: 'שלישי', timeSlot: 'שעה 1', gradeLevel: 'ה-ו' },
  { id: 447, name: 'אנגלית 4 קב\' 2 קרן', details: 'כיתה 40', day: 'שלישי', timeSlot: 'שעה 1', gradeLevel: 'ה-ו' },
  { id: 448, name: 'מספרים ופעולות 6 קב\' 1 איתי', details: 'כיתה 3', day: 'שלישי', timeSlot: 'שעה 1', gradeLevel: 'ה-ו' },
  { id: 449, name: 'מקהלה ד-ה-ו נועם', details: 'מוזיקה', day: 'שלישי', timeSlot: 'שעה 1', gradeLevel: 'ה-ו' },
  { id: 450, name: 'משחקי חצר ה-ו יוני', details: 'מגרש', day: 'שלישי', timeSlot: 'שעה 1', gradeLevel: 'ה-ו' },
  { id: 451, name: 'אותיות ומילים 6 קב\' 1 חן', details: 'כיתה 20', day: 'שלישי', timeSlot: 'שעה 2', gradeLevel: 'ה-ו' },
  { id: 452, name: 'מדע בכל פינה ד-ו קב\' 1 ניב', details: 'כיתה 40', day: 'שלישי', timeSlot: 'שעה 2', gradeLevel: 'ה-ו' },
  { id: 453, name: 'מספרים ופעולות 4 קב\' 2 איתי', details: 'כיתה 3', day: 'שלישי', timeSlot: 'שעה 2', gradeLevel: 'ה-ו' },
  { id: 454, name: 'מרכז תפירה ג-ו חוליאטה', details: 'אמנות', day: 'שלישי', timeSlot: 'שעה 2', gradeLevel: 'ה-ו' },
  { id: 455, name: 'הא ודא חוליאטה', details: 'כיתה כתומה', day: 'שלישי', timeSlot: 'שעה 3', gradeLevel: 'ה-ו' },
  { id: 456, name: 'הא ודא נעמה', details: 'כיתה 20', day: 'שלישי', timeSlot: 'שעה 3', gradeLevel: 'ה-ו' },
  { id: 457, name: 'הא ודא ניב', details: 'כיתה 40', day: 'שלישי', timeSlot: 'שעה 3', gradeLevel: 'ה-ו' },
  { id: 458, name: 'הא ודא יוני', details: 'כיתה 3', day: 'שלישי', timeSlot: 'שעה 3', gradeLevel: 'ה-ו' },
  { id: 459, name: 'שעת אבגד במגרש', details: '', day: 'שלישי', timeSlot: 'שעה 3', gradeLevel: 'ה-ו' },
  { id: 460, name: 'שעת וועדות (עד 13:00)', details: '', day: 'שלישי', timeSlot: 'שעה 4', gradeLevel: 'ה-ו' },
  { id: 461, name: 'ארוחה', details: '', day: 'שלישי', timeSlot: 'שעה 4', gradeLevel: 'ה-ו' },
  { id: 462, name: 'יום קצר עד 13:30', details: '', day: 'שלישי', timeSlot: 'שעה 5', gradeLevel: 'ה-ו' },

  // יום רביעי
  { id: 463, name: 'אותיות ומילים 5 חן', details: 'כיתה 20', day: 'רביעי', timeSlot: 'שעה 1', gradeLevel: 'ה-ו' },
  { id: 464, name: 'אנגלית 6 קב\' 2 גיא', details: 'כיתה 40', day: 'רביעי', timeSlot: 'שעה 1', gradeLevel: 'ה-ו' },
  { id: 465, name: 'מספרים ופעולות 4 קב\' 1 איתי', details: 'כיתה 3', day: 'רביעי', timeSlot: 'שעה 1', gradeLevel: 'ה-ו' },
  { id: 466, name: 'מקהלה ד-ה-ו נועם', details: 'מוזיקה', day: 'רביעי', timeSlot: 'שעה 1', gradeLevel: 'ה-ו' },
  { id: 467, name: 'ספורט ה-ו מריוס', details: 'אולם', day: 'רביעי', timeSlot: 'שעה 1', gradeLevel: 'ה-ו' },
  { id: 468, name: 'אותיות ומילים 6 קב\' 2 חן', details: 'כיתה 20', day: 'רביעי', timeSlot: 'שעה 2', gradeLevel: 'ה-ו' },
  { id: 469, name: 'אנגלית 4 קב\' 1 קרן', details: 'כיתה 40', day: 'רביעי', timeSlot: 'שעה 2', gradeLevel: 'ה-ו' },
  { id: 470, name: 'מספרים ופעולות 6 קב\' 2 איתי', details: 'כיתה 3', day: 'רביעי', timeSlot: 'שעה 2', gradeLevel: 'ה-ו' },
  { id: 471, name: 'מרכז תפירה ג-ו חוליאטה', details: 'אמנות', day: 'רביעי', timeSlot: 'שעה 2', gradeLevel: 'ה-ו' },
  { id: 472, name: 'אותיות ומילים 4 קב\' 2 חן', details: 'כיתה 20', day: 'רביעי', timeSlot: 'שעה 3', gradeLevel: 'ה-ו' },
  { id: 473, name: 'מדע בכל פינה ד-ו קב\' 2 ניב', details: 'כיתה 40', day: 'רביעי', timeSlot: 'שעה 3', gradeLevel: 'ה-ו' },
  { id: 474, name: 'מספרים ופעולות 5 קב\' 1 איתי', details: 'כיתה 3', day: 'רביעי', timeSlot: 'שעה 3', gradeLevel: 'ה-ו' },
  { id: 475, name: 'נולדו לבמה ה-ו יוני', details: 'אולם', day: 'רביעי', timeSlot: 'שעה 3', gradeLevel: 'ה-ו' },
  { id: 476, name: 'ארוחה', details: '', day: 'רביעי', timeSlot: 'שעה 4', gradeLevel: 'ה-ו' },
  { id: 477, name: 'אותיות ומילים 4 קב\' 1 חן', details: 'כיתה 20', day: 'רביעי', timeSlot: 'שעה 4', gradeLevel: 'ה-ו' },
  { id: 478, name: 'חיים בסרט ה-ו יוני', details: 'כיתה 40', day: 'רביעי', timeSlot: 'שעה 4', gradeLevel: 'ה-ו' },
  { id: 479, name: 'מספרים ופעולות 5 קב\' 2 איתי', details: 'כיתה 3', day: 'רביעי', timeSlot: 'שעה 4', gradeLevel: 'ה-ו' },
  { id: 480, name: 'שעת ללא כדורגל', details: 'במגרש', day: 'רביעי', timeSlot: 'שעה 4', gradeLevel: 'ה-ו' },
  { id: 481, name: 'ארוחה', details: '', day: 'רביעי', timeSlot: 'שעה 5', gradeLevel: 'ה-ו' },
  { id: 482, name: 'יזמות קהילתית ה-ו חוליאטה', details: 'כיתה 40', day: 'רביעי', timeSlot: 'שעה 5', gradeLevel: 'ה-ו' },
  { id: 483, name: 'חיזוקית חשבון 4-7 איתי', details: 'כיתה 3', day: 'רביעי', timeSlot: 'שעה 5', gradeLevel: 'ה-ו' },
  { id: 484, name: 'ריקודי עם מהצעד השני ב-ו חן', details: 'אולם', day: 'רביעי', timeSlot: 'שעה 5', gradeLevel: 'ה-ו' },
  { id: 485, name: 'כדורסל ה-ו מריוס', details: 'מגרש', day: 'רביעי', timeSlot: 'שעה 5', gradeLevel: 'ה-ו' },
  { id: 486, name: 'ספרדית ד-ה-ו חוליאטה', details: 'כיתה 20', day: 'רביעי', timeSlot: 'שעה 6', gradeLevel: 'ה-ו' },
  { id: 487, name: 'עיתון קהילה ד-ו יוני', details: 'כיתה 40', day: 'רביעי', timeSlot: 'שעה 6', gradeLevel: 'ה-ו' },
  { id: 488, name: 'קבוצת שירה ד-ה-ו נועם', details: 'מוזיקה', day: 'רביעי', timeSlot: 'שעה 6', gradeLevel: 'ה-ו' },

  // יום חמישי
  { id: 489, name: 'הספר הכי מפורסם בעולם ג-ו ארז', details: 'כיתה 20', day: 'חמישי', timeSlot: 'שעה 1', gradeLevel: 'ה-ו' },
  { id: 490, name: 'אנגלית 4 קב\' 2 קרן', details: 'כיתה 40', day: 'חמישי', timeSlot: 'שעה 1', gradeLevel: 'ה-ו' },
  { id: 491, name: 'מספרים ופעולות 6 קב\' 1 איתי', details: 'כיתה 3', day: 'חמישי', timeSlot: 'שעה 1', gradeLevel: 'ה-ו' },
  { id: 492, name: 'ספורט ה-ו מריוס', details: 'אולם', day: 'חמישי', timeSlot: 'שעה 1', gradeLevel: 'ה-ו' },
  { id: 493, name: 'המרכז ליצירת מרכזי פעילות קב\' 1 ארז', details: 'כיתה 20', day: 'חמישי', timeSlot: 'שעה 2', gradeLevel: 'ה-ו' },
  { id: 494, name: 'אנגלית 5 גיא', details: 'כיתה 40', day: 'חמישי', timeSlot: 'שעה 2', gradeLevel: 'ה-ו' },
  { id: 495, name: 'מספרים ופעולות 4 קב\' 2 איתי', details: 'כיתה 3', day: 'חמישי', timeSlot: 'שעה 2', gradeLevel: 'ה-ו' },
  { id: 496, name: 'מרכז אמנות פתוח דודי', details: 'אמנות', day: 'חמישי', timeSlot: 'שעה 2', gradeLevel: 'ה-ו' },
  { id: 497, name: 'מקום לשקט קב\' 2 קרן', details: 'אולם', day: 'חמישי', timeSlot: 'שעה 2', gradeLevel: 'ה-ו' },
  { id: 498, name: 'רצי קהילה ה-ו מריוס', details: 'מגרש', day: 'חמישי', timeSlot: 'שעה 2', gradeLevel: 'ה-ו' },
  { id: 499, name: 'אנגלית 6 קב\' 2 גיא', details: 'כיתה 40', day: 'חמישי', timeSlot: 'שעה 3', gradeLevel: 'ה-ו' },
  { id: 500, name: 'מספרים ופעולות 5 קב\' 2 איתי', details: 'כיתה 3', day: 'חמישי', timeSlot: 'שעה 3', gradeLevel: 'ה-ו' },
  { id: 501, name: 'ציור ה-ו דודי', details: 'אמנות', day: 'חמישי', timeSlot: 'שעה 3', gradeLevel: 'ה-ו' },
  { id: 502, name: 'ארוחה', details: '', day: 'חמישי', timeSlot: 'שעה 4', gradeLevel: 'ה-ו' },
  { id: 503, name: 'חלות', details: '', day: 'חמישי', timeSlot: 'שעה 4', gradeLevel: 'ה-ו' },
  { id: 504, name: 'ילד.ה בהפתעה ארז', details: 'כיתה 20', day: 'חמישי', timeSlot: 'שעה 4', gradeLevel: 'ה-ו' },
  { id: 505, name: 'מספרים ופעולות 5 קב\' 2 איתי', details: '2 איתי כיתה 3', day: 'חמישי', timeSlot: 'שעה 4', gradeLevel: 'ה-ו' },
  { id: 506, name: 'ארוחה', details: '', day: 'חמישי', timeSlot: 'שעה 5', gradeLevel: 'ה-ו' },
  { id: 507, name: 'חלות', details: '', day: 'חמישי', timeSlot: 'שעה 5', gradeLevel: 'ה-ו' },
  { id: 508, name: 'הורה בהפתעה כיתה 20', details: '', day: 'חמישי', timeSlot: 'שעה 5', gradeLevel: 'ה-ו' },
  { id: 509, name: 'סדנת מייקרים ד-ו דודי', details: 'אמנות', day: 'חמישי', timeSlot: 'שעה 5', gradeLevel: 'ה-ו' },
  { id: 510, name: 'כדורגל ה-ו מריוס', details: 'מגרש', day: 'חמישי', timeSlot: 'שעה 5', gradeLevel: 'ה-ו' },
  { id: 511, name: 'התפתחות גוף האדם ה-ו מריוס', details: 'כיתה 20', day: 'חמישי', timeSlot: 'שעה 6', gradeLevel: 'ה-ו' },
  { id: 512, name: 'פופ-אפ ה-ו יוני', details: 'כיתה 40', day: 'חמישי', timeSlot: 'שעה 6', gradeLevel: 'ה-ו' },
  { id: 513, name: 'שירה בלי ציבור ד-ה-ו קב\' 2 ניב', details: 'כיתה 3', day: 'חמישי', timeSlot: 'שעה 6', gradeLevel: 'ה-ו' },
  { id: 514, name: 'סדנת מייקרים ד-ו דודי', details: 'אמנות', day: 'חמישי', timeSlot: 'שעה 6', gradeLevel: 'ה-ו' },
  { id: 515, name: 'שעת ה-ו במגרש', details: '', day: 'חמישי', timeSlot: 'שעה 6', gradeLevel: 'ה-ו' },
];